apiVersion: v1
kind: Service
metadata:
  name: oauth2-server
  namespace: oauth2server  # Add the namespace here
spec:
  type: LoadBalancer  # Use LoadBalancer for cloud environments
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: oauth2-server-app